import {
  collection,
  addDoc,
  deleteDoc,
  doc,
  serverTimestamp,
  type WithFieldValue,
} from 'firebase/firestore';
import { db } from '@/lib/firebase/config';
import type { Offer } from '@/types';
import { errorEmitter } from '@/firebase/error-emitter';
import { FirestorePermissionError } from '@/firebase/errors';

// Input type excludes fields generated by the server
type OfferInput = Omit<Offer, 'id' | 'createdAt'>;

const offersCollection = collection(db, 'offers');

export const addOffer = (offerData: OfferInput) => {
  const dataWithTimestamp: WithFieldValue<OfferInput> = {
    ...offerData,
    createdAt: serverTimestamp(),
  };

  return addDoc(offersCollection, dataWithTimestamp).catch(async (serverError) => {
    const permissionError = new FirestorePermissionError({
      path: offersCollection.path,
      operation: 'create',
      requestResourceData: dataWithTimestamp,
    });
    errorEmitter.emit('permission-error', permissionError);
    throw serverError;
  });
};

export const deleteOffer = (id: string) => {
  const offerDoc = doc(db, 'offers', id);
  return deleteDoc(offerDoc).catch(async (serverError) => {
    const permissionError = new FirestorePermissionError({
      path: offerDoc.path,
      operation: 'delete',
    });
    errorEmitter.emit('permission-error', permissionError);
    throw serverError;
  });
};
