import {
  collection,
  addDoc,
  updateDoc,
  deleteDoc,
  doc,
  serverTimestamp,
  type WithFieldValue,
  getDocs,
  query,
  orderBy,
} from 'firebase/firestore';
import { db } from '@/lib/firebase/config';
import type { Product } from '@/types';
import { errorEmitter } from '@/firebase/error-emitter';
import { FirestorePermissionError } from '@/firebase/errors';

// The input type should not include fields that are auto-generated by Firestore.
type ProductInput = Omit<Product, 'id' | 'createdAt'>;
type ProductUpdateInput = Partial<ProductInput>;

const productsCollection = collection(db, 'products');

export const addProduct = (productData: ProductInput) => {
  const dataWithTimestamp: WithFieldValue<ProductInput> = {
    ...productData,
    createdAt: serverTimestamp(),
  };
  addDoc(productsCollection, dataWithTimestamp).catch(async (serverError) => {
    const permissionError = new FirestorePermissionError({
      path: productsCollection.path,
      operation: 'create',
      requestResourceData: dataWithTimestamp,
    });
    errorEmitter.emit('permission-error', permissionError);
  });
};

export const updateProduct = (id: string, productData: ProductUpdateInput) => {
  const productDoc = doc(db, 'products', id);
  updateDoc(productDoc, productData).catch(async (serverError) => {
    const permissionError = new FirestorePermissionError({
      path: productDoc.path,
      operation: 'update',
      requestResourceData: productData,
    });
    errorEmitter.emit('permission-error', permissionError);
  });
};

export const deleteProduct = (id: string) => {
  const productDoc = doc(db, 'products', id);
  deleteDoc(productDoc).catch(async (serverError) => {
    const permissionError = new FirestorePermissionError({
      path: productDoc.path,
      operation: 'delete',
    });
    errorEmitter.emit('permission-error', permissionError);
  });
};

export const getProducts = async (): Promise<Product[]> => {
  const q = query(collection(db, "products"), orderBy("name", "asc"));
  // The custom FirestorePermissionError is for client-side components.
  // For server-rendered pages, we let the error bubble up to Next.js.
  const querySnapshot = await getDocs(q);
  const products: Product[] = [];
  querySnapshot.forEach((doc) => {
    products.push({ id: doc.id, ...doc.data() } as Product);
  });
  return products;
};
