
import {
  collection,
  addDoc,
  serverTimestamp,
  type WithFieldValue,
} from 'firebase/firestore';
import { db } from '@/lib/firebase/config';
import type { PurchaseOrder } from '@/types';
import { errorEmitter } from '@/firebase/error-emitter';
import { FirestorePermissionError } from '@/firebase/errors';

// Input type excludes fields generated by the server
type PurchaseOrderInput = Omit<PurchaseOrder, 'id' | 'createdAt' | 'completedAt'>;

const purchaseOrdersCollection = collection(db, 'purchaseOrders');

export const addPurchaseOrder = (poData: PurchaseOrderInput) => {
  const dataWithTimestamp: WithFieldValue<PurchaseOrderInput> = {
    ...poData,
    createdAt: serverTimestamp(),
  };

  return addDoc(purchaseOrdersCollection, dataWithTimestamp).catch(async (serverError) => {
    const permissionError = new FirestorePermissionError({
      path: purchaseOrdersCollection.path,
      operation: 'create',
      requestResourceData: dataWithTimestamp,
    });
    errorEmitter.emit('permission-error', permissionError);
    throw serverError;
  });
};
